language: cpp
sudo: true

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libsfml-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
