language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

before_install:
  - sh .travis/before_install.sh

install: 
  - sh .travis/install.sh

script:
  - mkdir build
  - cd build
  - [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /opt/cmake/bin/cmake .. ; fi
  - [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ; fi
  - make
