language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

before_install:
  - chmod +x .travis/before_install.sh
  - chmod +x .travis/install.sh
  - ./.travis/before_install.sh

install: 
  - ./.travis/install.sh

script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /opt/cmake/bin/cmake ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ..; fi
  - make
