language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - sh .travis/before_install.sh

install: 
  - sh .travis/install.sh

script:
  - mkdir build
  - cd build
  - /opt/cmake/bin/cmake ..
  - make
